#!/bin/sh

command -v adb > /dev/null || { printf "%s\\n" "This script requires adb to be installed. Find it on the Internet and install it, then try again." >&2; exit 1; }
command -v zlib-flate > /dev/null || { printf "%s\\n" "This script requires zlib-flate (from package qpdf) to be installed. Install qpdf (e.g, using apt install or brew) and then try again." >&2; exit 1; }
command -v awk > /dev/null || { printf "%s\\n" "This script requires awk to be installed. Try installing awk, then try again." >&2; exit 1; }

set -e

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"; trap "" EXIT INT; kill -INT $$' HUP INT QUIT PIPE TERM
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir"

printf "%s\\n%s\\n" "This script assumes Android phone is attached to this computer via USB cable, and USB debugging is enabled on the phone." "USB debugging is set under Developer options (go to Settings/About device, then tap Build number 7 times to enable Developer options)" >&2

adb backup '-noapk com.android.providers.settings' -f settings.db >&2

if [ ! -s settings.db ]; then
  printf "%s\\n" "Error downloading settings from phone. Make sure phone has USB debugging enabled, and that you select option in dialog on phone to enable backup."
  exit 2
fi

dd if=settings.db bs=1 skip=24 2>/dev/null | zlib-flate -uncompress | tar -x
awk '/ssid="/{sub(/^\t/,"");SSID=$0}/psk="/{sub(/^\t/,"");printf("%s\n%s\n\n",SSID,$0)}' apps/com.android.providers.settings/f/flattened-data
